name: CI Test Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------- BACKEND TEST --------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Backend build & tests
        run: mvn -f backend/pom.xml test

      # -------- IA MODEL TEST --------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install IA dependencies
        run: |
          cd ai-model
          pip install -r requirements.txt

      - name: Run IA tests
        run: |
          cd ai-model
          python test_model.py
